# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ranger-base:latest

ARG RANGER_VERSION
ARG TARGETARCH
ARG RANGER_ADMIN_JAVA_VERSION

ENV JAVA_HOME=/usr/lib/jvm/java-1.${RANGER_ADMIN_JAVA_VERSION}.0-openjdk-${TARGETARCH}

RUN if [ "${OS_NAME}" = "UBUNTU" ]; then\
    update-java-alternatives --set "$JAVA_HOME";\
    fi

COPY ./ranger-docker/dist/version /home/ranger/dist/
COPY ./ranger-docker/dist/ranger-${RANGER_VERSION}-resource-mapping-manager.tar.gz /home/ranger/dist/

RUN tar xvfz /home/ranger/dist/ranger-${RANGER_VERSION}-resource-mapping-manager.tar.gz --directory=${RANGER_HOME} \
    && mv ${RANGER_HOME}/ranger-${RANGER_VERSION}-resource-mapping-manager ${RANGER_HOME}/rmm \
    && ln -s ${RANGER_HOME}/rmm/ranger-resource-mapping-manager-services.sh /usr/bin/ranger-resource-mapping-manager-services.sh \
    && rm -f /home/ranger/dist/ranger-${RANGER_VERSION}-resource-mapping-manager.tar.gz \
    && mkdir -p /var/run/ranger \
    && mkdir -p /var/log/ranger \
    && chown -R ranger:ranger ${RANGER_HOME}/rmm/ /var/run/ranger/ /var/log/ranger/ /usr/bin/ranger-resource-mapping-manager-services.sh \
    && mkdir -p /usr/share/java/

COPY ./resource-mapping-manager/rmm-docker-entrypoint.sh ${RANGER_HOME}/rmm/entrypoint.sh
COPY ./ranger-docker/downloads/postgresql-42.2.16.jre7.jar ${RANGER_HOME}/rmm/dist/
COPY ./resource-mapping-manager/conf/ranger-rmm-site.xml ${RANGER_HOME}/rmm/conf/

WORKDIR ${RANGER_HOME}/rmm

ENTRYPOINT [ "./entrypoint.sh" ]
