# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ranger-hadoop:latest

ARG HDFS_PLUGIN_VERSION
ARG HIVE_PLUGIN_VERSION

COPY ./ranger-docker/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz /home/ranger/dist/

RUN tar xvfz /home/ranger/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz --directory=/opt/ranger && \
    ln -s /opt/ranger/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin /opt/ranger/ranger-hive-plugin && \
    rm -f /home/ranger/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz && \
    cp /opt/ranger/ranger-hive-plugin/lib/ranger-hive-plugin-impl/*.jar /opt/ranger/ranger-hdfs-plugin/lib/ranger-hdfs-plugin-impl/ && \
    cp /opt/ranger/ranger-hdfs-plugin/ext/*.jar /opt/ranger/ranger-hdfs-plugin/lib/ranger-hdfs-plugin-impl/ && \
    rm /opt/ranger/ranger-${HDFS_PLUGIN_VERSION}-hdfs-plugin/install/conf.templates/enable/ranger-hdfs-security.xml

ENTRYPOINT [ "/home/ranger/scripts/ranger-hadoop.sh" ]
