# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ranger-ozone:latest

ARG OZONE_PLUGIN_VERSION
ARG OZONE_VERSION
ARG HIVE_PLUGIN_VERSION

COPY ./ranger-docker/dist/ranger-${OZONE_PLUGIN_VERSION}-ozone-plugin.tar.gz /etc/ozone-plugin/
COPY ./ranger-docker/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz /etc/hive/
COPY ./resource-mapping-manager/ozone-entrypoint.sh /etc/ozone/entrypoint.sh

RUN tar xvfz /etc/hive/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz --directory=/etc/hive && \
    ln -s /etc/hive/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin /etc/hive/ranger-hive-plugin && \
    rm -f /etc/hive/dist/ranger-${HIVE_PLUGIN_VERSION}-hive-plugin.tar.gz && \
    tar xvfz /etc/ozone-plugin/ranger-${OZONE_PLUGIN_VERSION}-ozone-plugin.tar.gz --directory=/etc/ozone-plugin && \
    mv /etc/ozone-plugin/ranger-${OZONE_PLUGIN_VERSION}-ozone-plugin /etc/ozone-plugin/ranger-ozone-plugin && \
    rm -f /etc/ozone-plugin/dist/ranger-${OZONE_PLUGIN_VERSION}-ozone-plugin.tar.gz
